project_name: omloxctl

git:
  tag_sort: "-version:creatordate"
  prerelease_suffix: "-"

builds:
  - main: ./cmd/omlox
    env:
      - CGO_ENABLED=0
    goos:
      - "linux"
      - "windows"
      - "darwin"
    goarch:
      - "amd64"
      - "arm64"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: 
      - "-s -w"
      - "-X main.version={{.Version}} -X main.commitHash={{.Commit}} -X main.buildDate={{.Date}}"

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-nightly"
changelog:
  use: "github-native"
  sort: "asc"
  filters:
    exclude:
      - "^docs:"
release:
  draft: false
  prerelease: "auto"
  mode: "replace"
